version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jobber-auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
